name: Build
on:
  push:
    branches:
      - master

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: |
            r1/${{ runner.os }}/npm/${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            r1/${{ runner.os }}/npm/

      - run: npm ci --legacy-peer-deps
      - run: CI=false npm run build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: deploy
          publish_dir: ./build
          force_orphan: true